env:
    rcloneconfig: "ENCRYPTED[68d6e2e07fa58a23f8c05fbd8405f4f36fcedc8e75fc91d3d5a4c3b8bac550e6f318f69b10b7926da0fbd6c624d81bde]"

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "Asyanx"
       - git config --global user.email "wowsanja2@gmail.com"
       - mkdir -p /tmp/ccache
       - rclone copy lo:ccache/ccache.tar.gz /tmp -P
       - cd /tmp
       - time tar xf ccache.tar.gz
       - cd /tmp
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
   
  Sync_script:
      - cd /tmp/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/ArcanaOS/project_manifest -b S -g default,-device,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      # DT/VT/KT/TC
      - git clone --depth=1 https://github.com/Asyanx/android_device_xiaomi_merlinx -b eleven device/xiaomi/merlinx
      - git clone --depth=1 https://github.com/Asyanx/android_vendor_xiaomi_merlinx vendor/xiaomi/merlinx
      - git clone --depth=1 https://github.com/ZpyLab/device_common -b twelve device/xiaomi/mt6768-common
      - git clone --depth=1 https://github.com/Asyanx/device_mediatek_sepolicy_vndr device/mediatek/sepolicy_vndr
      - git clone --depth=1 https://github.com/Asyanx/Rocket_Kernel_MT6768 kernel/xiaomi/mt6768

  Build_script:
      - cd /tmp/rom
      - export CCACHE_DIR=/tmp/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 20G
      - ccache -o compression=true
      - ccache -z
      - source build/envsetup.sh > /dev/null 2>&1
      - lunch aosp_merlinx-userdebug > /dev/null 2>&1
      - mka bacon -j8

  Upload_script:
      - rclone copy /tmp/rom/out/target/product/merlinx/ProjectArcana*.zip lo:merlinx -P
      - ./ziping.sh
      - cd /tmp
      - rclone copy ccache.tar.gz ccache -P
