env:
    rclone_config: "ENCRYPTED[68d6e2e07fa58a23f8c05fbd8405f4f36fcedc8e75fc91d3d5a4c3b8bac550e6f318f69b10b7926da0fbd6c624d81bde]"

task:
    name: Arcane
    timeout_in: 120m
    container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G      

    mengunduh_ccache_background_script:
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - df -h && free -h && nproc && cat /etc/os* && env
      - mkdir -p /tmp/ccache
      - rclone copy lo:ccache/ccache.tar.gz /tmp -P
      - cd /tmp
      - time tar xf ccache.tar.gz
      - ls /tmp
      - ls /tmp/ccache
      - rm -rf ccache.tar.gz
      - mkdir -p /tmp/rom
      - cd /tmp/rom
      - export CCACHE_DIR=/tmp/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 20G
      - ccache -o compression=true
      - ccache -z
    
    memantau_background_script:
      - ./memantau

    Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - cd /tmp/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/PixelExperience/manifest -b twelve -g default,-device,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      # DT/VT/KT/TC
      - git clone --depth=1 https://github.com/Asyanx/android_device_xiaomi_merlinx -b eleven device/xiaomi/merlinx
      - git clone --depth=1 https://github.com/Asyanx/android_vendor_xiaomi_merlinx vendor/xiaomi/merlinx
      - git clone --depth=1 https://github.com/ZpyLab/device_common -b twelve device/xiaomi/mt6768-common
      - git clone --depth=1 https://github.com/Asyanx/device_mediatek_sepolicy_vndr device/mediatek/sepolicy_vndr
      - git clone --depth=1 https://github.com/Asyanx/Rocket_Kernel_MT6768 kernel/xiaomi/mt6768
      - echo "============================"
      - echo "Sync Completed!"
      - echo "============================"

#    mengumpulkan_ccache_script:
#      - ./mengumpulkan_ccache
    membangun_akhir_script:
      - ./membangun_akhir
    mengunggah_script:
      - ./mengunggah
