#!/bin/bash

cd /tmp/rom

export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

. build/envsetup.sh
lunch xdroid_X01BD-userdebug
export KBUILD_BUILD_USER=android # Change with your own name or else.
export KBUILD_BUILD_HOST=mcrd1-19 # Change with your own hostname.
make xd -j8
