#!/bin/bash

cd /tmp/rom

export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

. build/envsetup.sh
lunch xdroid_X01BD-userdebug
export BUILD_USERNAME=aesxily
export SKIP_ABI_CHECKS=true
export SKIP_API_CHECKS=true
export KBUILD_BUILD_USER=aesxily
export KBUILD_BUILD_HOST=zepycloud
export ALLOW_MISSING_DEPENDENCIES=true
export TZ=Asia/Jakarta
make xd -j$(nproc --all)
