#!/bin/bash

cd /tmp/rom

export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

. build/envsetup.sh
lunch radiant_merlinx-userdebug
export BUILD_USERNAME=Slw
export SKIP_ABI_CHECKS=true
export SKIP_API_CHECKS=true
export KBUILD_BUILD_USER=Slw
export KBUILD_BUILD_HOST=SlwCloud
export ALLOW_MISSING_DEPENDENCIES=true
export TZ=Asia/Jakarta
mka bacon -j8
sleep 90m
kill %1
ccache -s
