#!/bin/bash

# Upload ROM
cd /tmp
time rclone copy /tmp/rom/out/target/product/merlinx/lineage-18.1*.zip lo:merlinx -P
cd /tmp/rom/out/target/product/merlinx/

# Upload ccache
cd /tmp

com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1

cd /tmp
time rclone copy ccache.tar.gz lo:ccache -P
