#!/bin/bash


cd /tmp

com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1

cd /tmp
time rclone copy /tmp/rom/out/target/product/X01BD/xd_rev*.zip ramadhannangga:X01BD -P
cd /tmp/rom/out/target/product/X01BD/
cd /tmp
time rclone copy ccache.tar.gz ramadhannangga:ccache -P
