#!/bin/bash

cd /tmp/rom

repo init -q --no-repo-verify --depth=1 -u https://github.com/PixelExperience/manifest -b eleven -g default,-device,-mips,-darwin,-notdefault
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Required Sources
git clone --depth=1 https://github.com/Asyanx/Device_Merlinx_Aex -b eleven device/xiaomi/merlinx
git clone --depth=1 https://github.com/Asyanx/android_vendor_xiaomi_merlinx vendor/xiaomi/merlinx
git clone --depth=1 https://github.com/Asyanx/Common_Merlinx-Aex -b eleven device/xiaomi/mt6768-common
git clone --depth=1 https://github.com/Asyanx/device_mediatek_sepolicy_vndr device/mediatek/sepolicy_vndr
git clone --depth=1 https://github.com/Asyanx/Rocket_Kernel_MT6768 kernel/xiaomi/mt6768
echo "synchronization done"
